import { DurationOption } from './types';

export const DURATION_OPTIONS: Array<{ label: string; value: DurationOption }> = [
  { label: 'Year to date', value: 'year_to_date' },
  { label: 'Last 12 months', value: 'ttm' },
  { label: 'Quarter to date', value: 'quarter_to_date' },
  { label: 'Month to date', value: 'month_to_date' },
  { label: 'Last month', value: 'last_month' },
  { label: 'Last quarter', value: 'last_quarter' },
  { label: 'Last year', value: 'last_year' },
];

export const METRIC_COLUMN_ORDER = [
  'Accounts',
  'ARR',
  'Renewals',
  'Renewal_revenue',
  'NRR',
  'Expected_billing',
  'Actual_billed',
  'Unpaid',
  'Amount_overdue',
  'Invoiced_ARR',
  'Insights_acted',
  'Tasks_done',
  'open_signals',
  'task',
  'opportunities',
  'value_of_opportunities',
  'opportunities_win_count',
  'opportunities_win_value',
  'opportunities_lost_count',
  'opportunities_lost_value',
  'risk_acted',
  'total_risks',
] as const;

export const METRIC_FIELD_MAP: Record<string, string> = {
  Accounts: 'accounts',
  ARR: 'arr',
  Renewal_revenue: 'actual_renewal_value',
  NRR: 'nrr',
  Expected_billing: 'expected_billing',
  Actual_billed: 'actual_billed',
  Unpaid: 'unpaid',
  Amount_overdue: 'total_amount_overdue',
  Invoiced_ARR: 'invoiced_arr',
  Insights_acted: 'insights_acted',
  Tasks_done: 'tasks',
  open_signals: 'open_signals',
  task: 'incomplete_tasks',
  opportunities: 'opportunities',
  value_of_opportunities: 'value_of_opportunities',
  opportunities_win_count: 'opportunities_win_count',
  opportunities_win_value: 'opportunities_win_value',
  opportunities_lost_count: 'opportunities_lost_count',
  opportunities_lost_value: 'opportunities_lost_value',
  risk_acted: 'risk_acted',
  total_risks: 'total_risks',
};
